TESTS = [
    {
        "id": "cbc",
        "name": "Complete Blood Count",
        "alt_names": ["CBC", "CBC with Differential", "CBC w/ Diff",
                      "Complete Blood Count with Differential"],
        "notes": None,
    },
    {
        "id": "cmp",
        "name": "Comprehensive Metabolic Panel",
        "alt_names": ["CMP", "Complete Metabolic Panel", "Chemistry Panel",
                      "14-Panel Chemistry"],
        "notes": None,
    },
    {
        "id": "lipid",
        "name": "Lipid Panel",
        "alt_names": ["Lipid Panel", "Cholesterol Panel", "Lipid Profile"],
        "notes": None,
    },
    {
        "id": "a1c",
        "name": "Hemoglobin A1c",
        "alt_names": ["HbA1c", "A1c", "Glycosylated Hemoglobin",
                      "Hemoglobin A1C", "Glycated Hemoglobin"],
        "notes": None,
    },
    {
        "id": "crp",
        "name": "C-Reactive Protein",
        "alt_names": ["CRP", "hsCRP", "High-Sensitivity CRP", "hs-CRP",
                      "C-Reactive Protein High Sensitivity"],
        "notes": "Prefer hsCRP over standard CRP. Flag which variant was matched.",
    },
    {
        "id": "insulin",
        "name": "Insulin, Fasting",
        "alt_names": ["Insulin", "Fasting Insulin", "Serum Insulin"],
        "notes": "Must be the fasting version.",
    },
    {
        "id": "lpa",
        "name": "Lipoprotein(a)",
        "alt_names": ["Lp(a)", "Lipoprotein a", "Lipoprotein-a"],
        "notes": "Units vary (mg/dL vs nmol/L). Record and flag unit.",
    },
    {
        "id": "apob",
        "name": "Apolipoprotein B",
        "alt_names": ["ApoB", "Apo B", "Apolipoprotein B-100"],
        "notes": None,
    },
    {
        "id": "tsh",
        "name": "Thyroid Stimulating Hormone",
        "alt_names": ["TSH", "Thyroid Stimulating Hormone", "Thyrotropin"],
        "notes": None,
    },
    {
        "id": "ft4",
        "name": "Free Thyroxine",
        "alt_names": ["Free T4", "FT4", "Free Thyroxine", "Thyroxine Free"],
        "notes": None,
    },
    {
        "id": "vitd",
        "name": "Vitamin D, 25-Hydroxyvitamin D",
        "alt_names": ["Vitamin D", "25-OH Vitamin D", "25-Hydroxyvitamin D",
                      "Vitamin D 25-Hydroxy", "Calcidiol"],
        "notes": "Prefer total D. Flag if only D2/D3 split is available.",
    },
    {
        "id": "b12",
        "name": "Vitamin B12",
        "alt_names": ["B12", "Vitamin B12", "Cobalamin", "Cyanocobalamin"],
        "notes": None,
    },
    {
        "id": "ferritin",
        "name": "Ferritin",
        "alt_names": ["Ferritin", "Serum Ferritin"],
        "notes": None,
    },
    {
        "id": "iron",
        "name": "Iron and Total Iron Binding Capacity",
        "alt_names": ["Iron Panel", "Iron and TIBC", "Iron Binding Capacity",
                      "Iron Studies", "Iron with TIBC"],
        "notes": None,
    },
    {
        "id": "total-test",
        "name": "Testosterone, Total",
        "alt_names": ["Total Testosterone", "Testosterone Total",
                      "Testosterone Serum"],
        "notes": "Flag LC-MS/MS vs immunoassay if visible.",
    },
    {
        "id": "free-test",
        "name": "Testosterone, Free",
        "alt_names": ["Free Testosterone", "Testosterone Free and Total",
                      "Free T"],
        "notes": "Flag calculated vs direct measurement.",
    },
    {
        "id": "estradiol",
        "name": "Estradiol",
        "alt_names": ["Estradiol", "Estradiol Sensitive", "E2",
                      "Estradiol LC/MS"],
        "notes": "Prefer sensitive/LC-MS assay. Flag assay type.",
    },
    {
        "id": "shbg",
        "name": "Sex Hormone Binding Globulin",
        "alt_names": ["SHBG", "Sex Hormone Binding Globulin",
                      "Sex Hormone-Binding Globulin"],
        "notes": None,
    },
    {
        "id": "psa",
        "name": "Prostate-Specific Antigen, Total",
        "alt_names": ["PSA", "PSA Total", "Prostate Specific Antigen",
                      "PSA Serum"],
        "notes": "Total PSA only. Flag if Free PSA ratio is bundled.",
    },
]
