TESTS = [
    # ── Original 19 tests ────────────────────────────────────────────
    {
        "id": "cbc",
        "name": "Complete Blood Count",
        "alt_names": ["CBC", "CBC with Differential", "CBC w/ Diff",
                      "Complete Blood Count with Differential"],
        "notes": None,
    },
    {
        "id": "cmp",
        "name": "Comprehensive Metabolic Panel",
        "alt_names": ["CMP", "Complete Metabolic Panel", "Chemistry Panel",
                      "14-Panel Chemistry"],
        "notes": None,
    },
    {
        "id": "lipid",
        "name": "Lipid Panel",
        "alt_names": ["Lipid Panel", "Cholesterol Panel", "Lipid Profile"],
        "notes": None,
    },
    {
        "id": "a1c",
        "name": "Hemoglobin A1c",
        "alt_names": ["HbA1c", "A1c", "Glycosylated Hemoglobin",
                      "Hemoglobin A1C", "Glycated Hemoglobin"],
        "notes": None,
    },
    {
        "id": "crp",
        "name": "C-Reactive Protein",
        "alt_names": ["CRP", "hsCRP", "High-Sensitivity CRP", "hs-CRP",
                      "C-Reactive Protein High Sensitivity"],
        "notes": "Prefer hsCRP over standard CRP. Flag which variant was matched.",
    },
    {
        "id": "insulin",
        "name": "Insulin, Fasting",
        "alt_names": ["Insulin", "Fasting Insulin", "Serum Insulin"],
        "notes": "Must be the fasting version.",
    },
    {
        "id": "lpa",
        "name": "Lipoprotein(a)",
        "alt_names": ["Lp(a)", "Lipoprotein a", "Lipoprotein-a"],
        "notes": "Units vary (mg/dL vs nmol/L). Record and flag unit.",
    },
    {
        "id": "apob",
        "name": "Apolipoprotein B",
        "alt_names": ["ApoB", "Apo B", "Apolipoprotein B-100"],
        "notes": None,
    },
    {
        "id": "tsh",
        "name": "Thyroid Stimulating Hormone",
        "alt_names": ["TSH", "Thyroid Stimulating Hormone", "Thyrotropin"],
        "notes": None,
    },
    {
        "id": "ft4",
        "name": "Free Thyroxine",
        "alt_names": ["Free T4", "FT4", "Free Thyroxine", "Thyroxine Free"],
        "notes": None,
    },
    {
        "id": "vitd",
        "name": "Vitamin D, 25-Hydroxyvitamin D",
        "alt_names": ["Vitamin D", "25-OH Vitamin D", "25-Hydroxyvitamin D",
                      "Vitamin D 25-Hydroxy", "Calcidiol"],
        "notes": "Prefer total D. Flag if only D2/D3 split is available.",
    },
    {
        "id": "b12",
        "name": "Vitamin B12",
        "alt_names": ["B12", "Vitamin B12", "Cobalamin", "Cyanocobalamin"],
        "notes": None,
    },
    {
        "id": "ferritin",
        "name": "Ferritin",
        "alt_names": ["Ferritin", "Serum Ferritin"],
        "notes": None,
    },
    {
        "id": "iron",
        "name": "Iron and Total Iron Binding Capacity",
        "alt_names": ["Iron Panel", "Iron and TIBC", "Iron Binding Capacity",
                      "Iron Studies", "Iron with TIBC"],
        "notes": None,
    },
    {
        "id": "total-test",
        "name": "Testosterone, Total",
        "alt_names": ["Total Testosterone", "Testosterone Total",
                      "Testosterone Serum"],
        "notes": "Flag LC-MS/MS vs immunoassay if visible.",
    },
    {
        "id": "free-test",
        "name": "Testosterone, Free",
        "alt_names": ["Free Testosterone", "Testosterone Free and Total",
                      "Free T"],
        "notes": "Flag calculated vs direct measurement.",
    },
    {
        "id": "estradiol",
        "name": "Estradiol",
        "alt_names": ["Estradiol", "Estradiol Sensitive", "E2",
                      "Estradiol LC/MS"],
        "notes": "Prefer sensitive/LC-MS assay. Flag assay type.",
    },
    {
        "id": "shbg",
        "name": "Sex Hormone Binding Globulin",
        "alt_names": ["SHBG", "Sex Hormone Binding Globulin",
                      "Sex Hormone-Binding Globulin"],
        "notes": None,
    },
    {
        "id": "psa",
        "name": "Prostate-Specific Antigen, Total",
        "alt_names": ["PSA", "PSA Total", "Prostate Specific Antigen",
                      "PSA Serum"],
        "notes": "Total PSA only. Flag if Free PSA ratio is bundled.",
    },

    # ── GoodLabs individual tests (added 2026-03-12) ─────────────────
    {"id": "acth",            "name": "ACTH, Plasma",                                          "alt_names": [], "notes": None},
    {"id": "aluminum",        "name": "Aluminum, Blood",                                        "alt_names": [], "notes": None},
    {"id": "amylase",         "name": "Amylase",                                                "alt_names": [], "notes": None},
    {"id": "ana",             "name": "ANA Screen, IFA, with Reflex to Titer and Pattern",      "alt_names": [], "notes": None},
    {"id": "androstenedione", "name": "Androstenedione",                                        "alt_names": [], "notes": None},
    {"id": "amh",             "name": "Anti-Mullerian Hormone (AMH)",                           "alt_names": ["AMH"], "notes": None},
    {"id": "arsenic",         "name": "Arsenic, Blood",                                         "alt_names": [], "notes": None},
    {"id": "c-peptide",       "name": "C-Peptide",                                              "alt_names": [], "notes": None},
    {"id": "ceruloplasmin",   "name": "Ceruloplasmin",                                          "alt_names": [], "notes": None},
    {"id": "coq10",           "name": "Coenzyme Q10, Total",                                    "alt_names": ["CoQ10"], "notes": None},
    {"id": "copper",          "name": "Copper, Serum or Plasma",                                "alt_names": ["Copper"], "notes": None},
    {"id": "cortisol",        "name": "Cortisol",                                               "alt_names": [], "notes": None},
    {"id": "cortisol-lcms",   "name": "Cortisol, Total, LC/MS",                                 "alt_names": [], "notes": "LC/MS assay."},
    {"id": "ck",              "name": "Creatine Kinase (CK), Total",                            "alt_names": ["CK", "CPK"], "notes": None},
    {"id": "crp-standard",    "name": "CRP",                                                    "alt_names": ["C-Reactive Protein"], "notes": "Standard CRP (not high-sensitivity). See crp ID for hs-CRP."},
    {"id": "cystatin-c",      "name": "Cystatin C",                                             "alt_names": [], "notes": None},
    {"id": "dhea-s",          "name": "DHEA-Sulfate",                                           "alt_names": ["DHEA-S", "DHEAS"], "notes": None},
    {"id": "dht",             "name": "Dihydrotestosterone (DHT)",                              "alt_names": ["DHT"], "notes": None},
    {"id": "estradiol-lcms",  "name": "Estradiol, Sensitive, LC/MS",                            "alt_names": [], "notes": "Sensitive LC/MS assay. See estradiol ID for standard immunoassay."},
    {"id": "estrogens-total", "name": "Estrogens, Total, Immunoassay",                          "alt_names": [], "notes": None},
    {"id": "estrone",         "name": "Estrone",                                                "alt_names": ["E1"], "notes": None},
    {"id": "fibrinogen",      "name": "Fibrinogen",                                             "alt_names": [], "notes": None},
    {"id": "folate-rbc",      "name": "Folate, RBC",                                            "alt_names": ["RBC Folate"], "notes": None},
    {"id": "folate-serum",    "name": "Folate, Serum",                                          "alt_names": ["Serum Folate", "Vitamin B9"], "notes": None},
    {"id": "fructosamine",    "name": "Fructosamine",                                           "alt_names": [], "notes": None},
    {"id": "fsh",             "name": "FSH",                                                    "alt_names": ["Follicle-Stimulating Hormone"], "notes": None},
    {"id": "gastrin",         "name": "Gastrin",                                                "alt_names": [], "notes": None},
    {"id": "ggt",             "name": "GGT",                                                    "alt_names": ["Gamma-Glutamyl Transferase"], "notes": None},
    {"id": "glucose",         "name": "Glucose",                                                "alt_names": ["Blood Glucose", "Fasting Glucose"], "notes": None},
    {"id": "gh",              "name": "Growth Hormone (GH)",                                    "alt_names": ["GH", "HGH"], "notes": None},
    {"id": "hemoglobin",      "name": "Hemoglobin (Hb)",                                        "alt_names": ["Hb", "Hgb"], "notes": None},
    {"id": "hep-c",           "name": "Hepatitis C Antibody",                                   "alt_names": ["HCV", "Hep C"], "notes": None},
    {"id": "homocysteine",    "name": "Homocysteine",                                           "alt_names": [], "notes": None},
    {"id": "iga",             "name": "Immunoglobulin A (IgA) - Serum",                         "alt_names": ["IgA"], "notes": None},
    {"id": "inhibin-b",       "name": "Inhibin B",                                              "alt_names": [], "notes": None},
    {"id": "igf1",            "name": "Insulin-Like Growth Factor I (IGF-1) LC/MS",             "alt_names": ["IGF-1", "IGF1"], "notes": None},
    {"id": "il1b",            "name": "Interleukin-1 Beta (IL-1β)",                             "alt_names": ["IL-1 Beta", "IL-1b"], "notes": None},
    {"id": "il6",             "name": "Interleukin-6 (IL-6)",                                   "alt_names": ["IL-6"], "notes": None},
    {"id": "iodine-urine",    "name": "Iodine, Random Urine",                                   "alt_names": [], "notes": "Urine collection."},
    {"id": "iodine-serum",    "name": "Iodine, Serum/Plasma",                                   "alt_names": [], "notes": None},
    {"id": "ldl-direct",      "name": "LDL Cholesterol (Direct)",                               "alt_names": ["LDL Direct", "Direct LDL"], "notes": None},
    {"id": "lead",            "name": "Lead (Venous)",                                          "alt_names": ["Lead", "Blood Lead"], "notes": None},
    {"id": "leptin",          "name": "Leptin",                                                 "alt_names": [], "notes": None},
    {"id": "lh",              "name": "LH",                                                     "alt_names": ["Luteinizing Hormone"], "notes": None},
    {"id": "lipase",          "name": "Lipase",                                                 "alt_names": [], "notes": None},
    {"id": "lp-pla2",         "name": "Lp-PLA2 Activity",                                       "alt_names": ["LpPLA2"], "notes": None},
    {"id": "magnesium-rbc",   "name": "Magnesium, RBC",                                         "alt_names": ["RBC Magnesium"], "notes": "RBC (intracellular) assay. Different from serum magnesium."},
    {"id": "mercury",         "name": "Mercury, Blood",                                         "alt_names": ["Blood Mercury"], "notes": None},
    {"id": "methylmalonic",   "name": "Methylmalonic Acid",                                     "alt_names": ["MMA"], "notes": None},
    {"id": "methylmalonic-s", "name": "Methylmalonic Acid, Serum",                              "alt_names": ["MMA Serum"], "notes": "Serum-specific assay."},
    {"id": "molybdenum",      "name": "Molybdenum, Serum or Plasma",                            "alt_names": [], "notes": None},
    {"id": "mthfr",           "name": "MTHFR Genetic Test",                                     "alt_names": ["MTHFR"], "notes": "Genetic test — single order, not repeatable."},
    {"id": "nt-probnp",       "name": "NT-proBNP",                                              "alt_names": ["NT proBNP", "BNP"], "notes": None},
    {"id": "oxldl",           "name": "OxLDL",                                                  "alt_names": ["Oxidized LDL"], "notes": None},
    {"id": "pregnenolone",    "name": "Pregnenolone, MS",                                       "alt_names": ["Pregnenolone"], "notes": "LC/MS assay."},
    {"id": "progesterone",    "name": "Progesterone",                                           "alt_names": [], "notes": None},
    {"id": "progesterone-lcms", "name": "Progesterone, LC/MS",                                  "alt_names": [], "notes": "LC/MS assay. See progesterone for standard immunoassay."},
    {"id": "prolactin",       "name": "Prolactin",                                              "alt_names": [], "notes": None},
    {"id": "pth",             "name": "PTH, Intact without Calcium",                            "alt_names": ["PTH", "Parathyroid Hormone"], "notes": None},
    {"id": "rbc-copper",      "name": "RBC Copper",                                             "alt_names": [], "notes": "RBC (intracellular) assay."},
    {"id": "reverse-t3",      "name": "Reverse T3 Serum/Plasma",                               "alt_names": ["Reverse T3", "rT3"], "notes": None},
    {"id": "rf",              "name": "Rheumatoid Factor",                                      "alt_names": ["RF", "Rheumatoid Factor"], "notes": None},
    {"id": "rpr",             "name": "RPR (Rapid Plasma Reagin) - Syphilis Screening",         "alt_names": ["RPR", "Syphilis Screen"], "notes": None},
    {"id": "esr",             "name": "Sedimentation Rate-Westergren (ESR)",                    "alt_names": ["ESR", "Sed Rate"], "notes": None},
    {"id": "selenium",        "name": "Selenium, Serum or Plasma",                              "alt_names": ["Selenium"], "notes": None},
    {"id": "serum-amyloid-a", "name": "Serum Amyloid A",                                        "alt_names": ["SAA"], "notes": None},
    {"id": "t3-reverse-lcms", "name": "T3 Reverse, LC/MS/MS",                                  "alt_names": [], "notes": "LC/MS assay. See reverse-t3 for standard assay."},
    {"id": "t3-total",        "name": "T3 Total",                                               "alt_names": ["Total T3", "Triiodothyronine Total"], "notes": None},
    {"id": "t3-uptake",       "name": "T3 Uptake",                                              "alt_names": [], "notes": None},
    {"id": "t4-total",        "name": "T4 (Thyroxine), Total",                                  "alt_names": ["Total T4", "T4 Total"], "notes": None},
    {"id": "t3-free",         "name": "Triiodothyronine (T3), Free",                            "alt_names": ["Free T3", "FT3"], "notes": None},
    {"id": "tg-antibody",     "name": "Thyroglobulin Antibody",                                 "alt_names": ["TgAb", "Anti-Thyroglobulin"], "notes": None},
    {"id": "tpo",             "name": "Thyroid Peroxidase Antibody (TPO)",                      "alt_names": ["TPO", "Anti-TPO"], "notes": None},
    {"id": "transferrin",     "name": "Transferrin",                                            "alt_names": [], "notes": None},
    {"id": "uric-acid",       "name": "Uric Acid",                                              "alt_names": ["Uric Acid", "Gout Test"], "notes": None},
    {"id": "urinalysis",      "name": "Urinalysis",                                             "alt_names": ["UA", "Urine Analysis"], "notes": None},
    {"id": "vita",            "name": "Vitamin A, Serum or Plasma",                             "alt_names": ["Vitamin A", "Retinol"], "notes": None},
    {"id": "vitb1",           "name": "Vitamin B1 (Thiamine), Whole Blood",                     "alt_names": ["Vitamin B1", "Thiamine"], "notes": None},
    {"id": "vitb2",           "name": "Vitamin B2 (Riboflavin)",                                "alt_names": ["Vitamin B2", "Riboflavin"], "notes": None},
    {"id": "vitb6",           "name": "Vitamin B6, Plasma",                                     "alt_names": ["Vitamin B6", "Pyridoxine"], "notes": None},
    {"id": "zinc-rbc",        "name": "Zinc, RBC",                                              "alt_names": [], "notes": "RBC (intracellular) assay."},
    {"id": "zinc-serum",      "name": "Zinc, Serum or Plasma",                                  "alt_names": ["Zinc"], "notes": None},

    # ── GoodLabs bundle tests (added 2026-03-12) ─────────────────────
    {"id": "abo-rh",             "name": "ABO Group and Rh Type",                                                          "alt_names": ["Blood Type", "ABO/Rh"],    "bundle": True, "notes": None},
    {"id": "aldo-renin",         "name": "Aldosterone/Plasma Renin Activity Ratio",                                        "alt_names": [],                          "bundle": True, "notes": None},
    {"id": "albumin-urine",      "name": "Albumin, Random Urine with Creatinine",                                          "alt_names": ["Microalbumin"],             "bundle": True, "notes": None},
    {"id": "anemia-panel",       "name": "Anemia",                                                                         "alt_names": ["Anemia Panel"],             "bundle": True, "notes": None},
    {"id": "celiac",             "name": "Celiac Disease Antibody Evaluation",                                             "alt_names": ["Celiac Panel"],             "bundle": True, "notes": None},
    {"id": "ct-ng",              "name": "Chlamydia/Neisseria gonorrhoeae",                                                "alt_names": ["CT/NG", "Chlamydia/Gonorrhea"], "bundle": True, "notes": None},
    {"id": "comp-mens",          "name": "Comprehensive Men's",                                                            "alt_names": [],                          "bundle": True, "notes": None},
    {"id": "comp-womens",        "name": "Comprehensive Women's",                                                          "alt_names": [],                          "bundle": True, "notes": None},
    {"id": "dht-free",           "name": "Dihydrotestosterone (DHT), Free, LC/MS/Dialysis",                               "alt_names": [],                          "bundle": True, "notes": "Equilibrium dialysis method."},
    {"id": "estrogens-frac",     "name": "Estrogens, Fractionated, LC/MS",                                                "alt_names": [],                          "bundle": True, "notes": None},
    {"id": "fsh-lh",             "name": "FSH and LH",                                                                    "alt_names": ["FSH/LH"],                  "bundle": True, "notes": None},
    {"id": "full-monty",         "name": "Full Monty",                                                                    "alt_names": [],                          "bundle": True, "notes": "GoodLabs comprehensive panel."},
    {"id": "gtt",                "name": "Glucose Tolerance Test (GTT), Two Hour Oral (WHO Protocol)",                    "alt_names": ["GTT", "Glucose Tolerance"], "bundle": True, "notes": None},
    {"id": "heart-health",       "name": "Heart Health",                                                                  "alt_names": [],                          "bundle": True, "notes": None},
    {"id": "heavy-metals",       "name": "Heavy Metals",                                                                  "alt_names": ["Heavy Metals Panel"],       "bundle": True, "notes": None},
    {"id": "hb-frac",            "name": "Hemoglobinopathy Fractionation Cascade",                                        "alt_names": [],                          "bundle": True, "notes": None},
    {"id": "hiv",                "name": "HIV-1/2 Antigen and Antibodies, Fourth Generation, with Reflexes",              "alt_names": ["HIV", "HIV Test"],          "bundle": True, "notes": None},
    {"id": "iron-tibc",          "name": "Iron and TIBC",                                                                 "alt_names": ["Iron/TIBC"],               "bundle": True, "notes": "Iron + TIBC only — excludes ferritin. See iron ID for full panel."},
    {"id": "mens-hormone",       "name": "Men's Hormone",                                                                 "alt_names": [],                          "bundle": True, "notes": None},
    {"id": "metabolic-health",   "name": "Metabolic Health",                                                              "alt_names": [],                          "bundle": True, "notes": None},
    {"id": "nmr-lipo",           "name": "NMR LipoProfile",                                                              "alt_names": ["NMR Lipoprofile"],          "bundle": True, "notes": None},
    {"id": "nutrient-panel",     "name": "Nutrient",                                                                     "alt_names": ["Nutrient Panel"],           "bundle": True, "notes": None},
    {"id": "omegacheck",         "name": "OmegaCheck",                                                                   "alt_names": ["Omega-3", "OmegaCheck"],    "bundle": True, "notes": None},
    {"id": "ogtt",               "name": "Oral Glucose + Insulin Tolerance Test over 2 hours (4 Specimens) (OGTT)",      "alt_names": ["OGTT"],                    "bundle": True, "notes": None},
    {"id": "prolactin-total",    "name": "Prolactin, Total and Monomeric",                                               "alt_names": [],                          "bundle": True, "notes": None},
    {"id": "psa-free",           "name": "PSA Total+% Free",                                                             "alt_names": ["PSA Free", "PSA with Free Fraction"], "bundle": True, "notes": None},
    {"id": "pt-inr",             "name": "PT w/INR",                                                                     "alt_names": ["PT/INR", "Prothrombin Time"], "bundle": True, "notes": None},
    {"id": "reticulocyte",       "name": "Reticulocyte Count",                                                           "alt_names": ["Retics"],                  "bundle": True, "notes": None},
    {"id": "std-screening",      "name": "STD Screening",                                                                "alt_names": ["STI Screening"],           "bundle": True, "notes": None},
    {"id": "test-free-total",    "name": "Testosterone, Free and Total, MS",                                             "alt_names": [],                          "bundle": True, "notes": "Bundle. See free-test for the matching standalone entry."},
    {"id": "test-free-bio-total","name": "Testosterone, Free, Bioavailable and Total, MS",                               "alt_names": [],                          "bundle": True, "notes": None},
    {"id": "test-calc-shbg",     "name": "Testosterone, Free (Calculated) and Total, SHBG, Albumin",                     "alt_names": [],                          "bundle": True, "notes": None},
    {"id": "ttg",                "name": "Tissue Transglutaminase (tTG) Antibodies (IgA, IgG)",                          "alt_names": ["tTG", "TTG Antibodies"],   "bundle": True, "notes": None},
    {"id": "thyroid-panel",      "name": "Thyroid",                                                                      "alt_names": ["Thyroid Panel"],           "bundle": True, "notes": None},
    {"id": "womens-hormone",     "name": "Women's Hormone",                                                              "alt_names": [],                          "bundle": True, "notes": None},
    {"id": "body-builder",       "name": "Body Builder Panel",                                                           "alt_names": [],                          "bundle": True, "notes": None},
]
